### ISSUE TITLE
Problem matcher should pick up traces

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#139]
see https://github.com/vshaxe/vshaxe/issues/138

**Comment by Gama11** [comment]
I think this is only going to work by defining a separate `haxe-trace` problem matcher, meaning users would have to adjust their `tasks.json`:

```json
"problemMatcher": ["$haxe", "$haxe-trace"]
```

Not sure if it's worth it if it doesn't just work automatically (@ncannasse)? On the other hand, once we generate tasks with the new API, we can just add both and the users won't have to worry about it.

**Comment by ncannasse** [comment]
Seems good to me

**Comment by Gama11** [comment]
Actually, this doesn't work so well... traces usually output something like `Main.hx`, but you'd need the classpath prefixed: `source/Main.hx`. Probably not worth showing in the problems panel if it's not clickable.

**Comment by ncannasse** [comment]
This problem about class path prefix really overlaps with #23 which is the topmost annoying issue for me right now as I often develop on both application and libraries in same workspace (a game and its libraries for instance).

I highly recommand you take VSCode_HL approach in order to rebuild the class path in the Haxe adapter in order to be able to both display trace and fix #23 https://github.com/ncannasse/vscode_hl/blob/master/src/HLAdapter.hx#L104

**Comment by Gama11** [comment]
We actually can't do that, there's no VSHaxe code running for problem matching.. It's basically just a regex defined in package.json that VSCode matches against task output. So there's no opportunity to adjust paths.

**Comment by ncannasse** [comment]
@Gama11 : but our output comes from another task right? since we connect to haxe server. So it's more about preprocessing at this level

**Comment by Gama11** [comment]
Actually, it looks like this _does_ work properly for traces from within macros, since the classpath is prefixed there:

```
source/Main.hx:9: foo
```

It's just that other targets don't do that. So if you have a hxml task with something like `-cmd node output.js`, you might expect the trace to be picked up there too (and it is), but navigation to the source doesn't work.

Is there a reason for this discrepancy? Shouldn't other targets prefix the classpath too?

**Comment by ncannasse** [comment]
@Gama11 I have fixed something related to this today, please update haxe :)

**Comment by Gama11** [comment]
Heh, nice coincidence. That helps indeed. 👍

**Comment by Gama11** [comment]
Note: we still have a similar issue here as we did with #23, you can't navigate to traces within haxelibs. Doesn't seem like we can do anything about that on the vshaxe side though, Haxe outputs those as relative paths:

```
format/agal/Data.hx:30: foo
```
