### ISSUE TITLE
Migration: please emit ES6 output

### ISSUE THREAD

**Issue by jrieken** [vshaxe/vshaxe#317]
We have identified this extension as emitting ES5-JavaScript code *and* extending API-types, like `vscode.Disposable` or `vscode.CompletionItem`. VS Code itself has changed to emit ES6 JavaScript code and too enable `functions` extending from `classes` we have added a utility in our code. Given the small number of es5-emitting extensions that also extend API-types we ask for your help, which is emitting ES6 instead of ES5. 

Thanks and #HappyCoding

**Comment by nadako** [comment]
This will require changes in the Haxe compiler to make it able to output ES6. I'm going to work on that because there's more and more libs designed to extend ES6 classes, especially of course VS Code that's going to drop ES5 support so our extension will just stop working.

**Comment by jrieken** [comment]
> especially of course VS Code that's going to drop ES5 support so our extension will just stop working.

Be assured that we won't be that aggressive. The issue is only with ES5 "classes" extending ES6 classes and it would be nice if all extensions use es6 so that we can stop supporting both worlds.

**Comment by nadako** [comment]
I think we're now ES6-ready. @Gama11 can you confirm with the Insiders build?

**Comment by Gama11** [comment]
@jrieken Well, as I mentioned in https://github.com/Microsoft/vscode/issues/68698 some things had already stopped working in Insider's despite the backwards compatibility layer.

Anyway, as @nadako says, we have switched to ES6 output and as far as I can tell, everything is working in current Insider's builds. I just hadn't closed this yet since we haven't made a release with that yet.

**Comment by jrieken** [comment]
> some things had already stopped working in Insider's despite the backwards compatibility layer.

Well, you pointed to some stack trace which is valid error but unrelated to supporting es5 or es6. It was a bug that we have fixed.

**Comment by Gama11** [comment]
Hm... are you sure about that? That same error still happens with current Insider's builds if I switch back to ES5 output.

**Comment by jrieken** [comment]
The error is about calling `toLowerCase` on `undefined` and I would be surprised if the ES6 compile triggered that. Tho, you never know. What's that code on the haxe side doing? You do have a source pointer?

**Comment by Gama11** [comment]
It seems that `label` ends up being `undefined` for our `Node` class that extends `vscode.TreeItem`. This particular crash actually doesn't trigger anymore with current builds of the extension [because of some null safety changes I made](https://github.com/vshaxe/vshaxe/blob/master/src/vshaxe/view/dependencies/Node.hx#L54).

However, the `label` still seems to be `undefined` regardless, because VSCode uses the `resourceUri` to determine the tree item label in Insider's builds with ES5 output:

![](https://i.imgur.com/dAwRPut.png)

vs how it's meant to look (and does, with ES6 output):

![](https://i.imgur.com/TG9XtEH.png)

I guess it comes down to the `super(label)` call no longer working for some reason. An explicit `this.label = label;` in the `Node` constructor also fixes it.

**Comment by Gama11** [comment]
Haxe translates `super` calls to this in ES5 mode:

```js
vshaxe.view.dependencies.Node = function(parent,label,path,type) {
	vscode.TreeItem.call(this,label);
        ...
```

**Comment by jrieken** [comment]
Hm, it doesn't return the result of calling `TreeItem.call(...)`, right? that's how the built-in `__extends` of TypeScript and Babel do it. With that I can see how the custom `Node` object has the right properties set

**Comment by Gama11** [comment]
Interesting. :) There's indeed nothing returned from the constructor.

**Comment by Gama11** [comment]
We just released 2.7.0 with ES6 output.
