### ISSUE TITLE
Support javadoc-style multiline comments

### ISSUE THREAD

**Issue by gene-pavlovsky** [vshaxe/vshaxe#535]
When working on a `.js` file in VS Code, javadoc-style multiline comments are supported:
I.e. when you type `/**` and press enter, the caret goes to a new line and ` * ` is automatically inserted. When you close the comment with ` */`, the caret goes back to the correct indentation level. There is [an issue](https://github.com/microsoft/vscode/issues/155165) when pasting code, though.

When working on a `.hx` file, typing `/**` and pressing enter results in the caret going to a new line, one full indentation level to the right. If ` * ` is inserted manually, pressing enter keeps the indentation on the same level (doesn't automatically insert further `*`). Furthermore, when the comment is closed ` */`, pressing enter goes to a new line, keeping indentation on the same level (including one undesirable space).

It would be nice if it was possible to naturally write javadoc-style comments in Haxe code, such as it works for `.js` (quite likely not only JS, I just didn't try other languages).

**Comment by rushmobius** [comment]
Previously codedox worked fine. I think it is currently broken due to https://github.com/vshaxe/vshaxe/issues/534 So this is possibly a dupe?

**Comment by AlexHaxe** [comment]
I assume this is fixed by latest codedox update.

**Comment by gene-pavlovsky** [comment]
I can confirm that after installing the codedox extension (in addition to vshaxe), the feature works as expected.
The VS Code issue with pasting is still present, but is not specific to Haxe code.
Shouldn't this codedox ext be bundled with vshaxe? How are people supposed to find out about it?
