### ISSUE TITLE
Some display modes don't explore the entire classpath

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#96]
Original issue: https://github.com/vshaxe/haxe-languageserver/issues/5

For instance, "Find All References" does _not_ find all references in the project's classpaths. That's because usage completion only sees modules that are being compiled, not everything in the classpath.

This affects other features too, e.g. the "import" code action from diagnostics.

**Comment by EricBishton** [comment]
Is this a bug with haxe-languageserver or the compiler services?

**Comment by Gama11** [comment]
Quoting the comments from the original issue since it's not accessible anymore:

@nadako: 
>I'd like to have this working properly (i.e. not only in current file).

>@Simn how it should be done wrt haxe? should languageserver maintain the list of `.hx` files in the project, be aware of classpaths and convert those files to qualified module paths and pass them to haxe compiler?

@Simn: 
>I was thinking to utilize `--macro include` somehow but you easily run the risk of including stuff that is not meant to be used on the current target. I'm inclined to think that usage completion really requires a normal build step through the compilation server first.

**Comment by Gama11** [comment]
So, in summary, it's not really clear where this should be solved. It's just a limitation with regards to how display modes work right now, and there are potential workarounds like `--macro include`.

https://github.com/vshaxe/vshaxe/issues/79 might help with solving this, as Simn mentioned:

>I'm inclined to think that usage completion really requires a normal build step through the compilation server first.

**Comment by nadako** [comment]
Nowadays I'm very much positive that to solve this properly, we should have a declarative project format that is used for both compiler services and compilation itself, instead of trying to mess with compiler arguments. I want to experiment with designing such format, but couldn't carve time for that yet.

**Comment by nadako** [comment]
Tho even if we have such thing, it's still not clear when and how compiler would update its cache.

**Comment by Gama11** [comment]
>Tho even if we have such thing, it's still not clear when and how compiler would update its cache.

This would just happen automatically if we build through the display server - again, https://github.com/vshaxe/vshaxe/issues/79.

**Comment by nadako** [comment]
Yes, but I think that's just a workaround. Ideally you just add something and it appears in the indexes.

**Comment by Gama11** [comment]
Agreed. But if you build through the display server, that means vshaxe controls the build process, and then you can just run a build (with no output) in the background every so often when needed.

**Comment by nadako** [comment]
Given that cache server is working properly :-P

**Comment by Gama11** [comment]
Yes, there's a lot of ifs here...

**Comment by nadako** [comment]
Anyway, I've written down my basic vision of what would help here: https://github.com/nadako/haxe/wiki/hxproject

**Comment by Gama11** [comment]
Related Haxe issue: https://github.com/HaxeFoundation/haxe/issues/7004

(note: for toplevel completion, everything is explored now)

**Comment by Gama11** [comment]
The corresponding Haxe issue has been closed, and as far as I can tell, Find References now actually finds all references. :)
